// Mappings for common Minecraft items that might not be in the recipes data
export const MINECRAFT_ITEM_NAMES: Record<string, string> = {
  // Basic materials
  QUARTZ: "Nether Quartz",
  ENDER_PEARL: "Ender Pearl",
  FLINT: "Flint",
  OBSIDIAN: "Obsidian",
  MITHRIL_ORE: "Mithril Ore",
  NULL_SPHERE: "Null Sphere",
  TARANTULA_WEB: "Tarantula Web",
  SOUL_STRING: "Soul String",
  GRIFFIN_FEATHER: "Griffin Feather",

  // Blocks and materials
  LAPIS_LAZULI: "Lapis Lazuli",
  IRON_INGOT: "Iron Ingot",
  GOLD_INGOT: "Gold Ingot",
  COAL: "Coal",
  REDSTONE: "Redstone",
  EMERALD: "Emerald",
  "INK_SACK-4": "Lapis Lazuli",
  SLIME_BALL: "Slime Ball",
  DIAMOND: "Diamond",
  ROTTEN_FLESH: "Rotten Flesh",
  BONE: "Bone",
  STRING: "String",
  GUNPOWDER: "Gunpowder",
  SPIDER_EYE: "Spider Eye",
  BLAZE_POWDER: "Blaze Powder",
  BLAZE_ROD: "Blaze Rod",
  GHAST_TEAR: "Ghast Tear",
  NETHER_WART: "Nether Wart",
  MAGMA_CREAM: "Magma Cream",
  FERMENTED_SPIDER_EYE: "Fermented Spider Eye",
  GLISTERING_MELON: "Glistering Melon",
  GOLDEN_CARROT: "Golden Carrot",
  RABBIT_FOOT: "Rabbit's Foot",
  TURTLE_HELMET: "Turtle Shell",
  PHANTOM_MEMBRANE: "Phantom Membrane",

  // Wood types
  LOG: "Oak Log",
  LOG_2: "Dark Oak Log",
  WOOD: "Oak Wood",

  // Wool colors
  WOOL: "White Wool",
  STAINED_CLAY: "Terracotta",

  // Common skyblock items
  ENCHANTED_BOOK: "Enchanted Book",
  GOLDEN_APPLE: "Golden Apple",
  ENCHANTED_GOLDEN_APPLE: "Enchanted Golden Apple",

  // Additional items from the screenshot
  GILLS: "Gills",
  NULL_OVOID: "Null Ovoid",
  NULL_EDGE: "Null Edge",
  ENCHANTED_QUARTZ_BLOCK: "Enchanted Quartz Block",
  TARANTULA_SILK: "Tarantula Silk",
};

// Mappings for common Minecraft item IDs for images
export const MINECRAFT_ITEM_IDS: Record<string, string> = {
  QUARTZ: "quartz",
  ENDER_PEARL: "ender_pearl",
  FLINT: "flint",
  OBSIDIAN: "obsidian",
  LAPIS_LAZULI: "lapis_lazuli",
  IRON_INGOT: "iron_ingot",
  GOLD_INGOT: "gold_ingot",
  COAL: "coal",
  REDSTONE: "redstone",
  EMERALD: "emerald",
  "INK_SACK-4": "lapis_lazuli",
  SLIME_BALL: "slime_ball",
  DIAMOND: "diamond",
  ROTTEN_FLESH: "rotten_flesh",
  BONE: "bone",
  STRING: "string",
  GUNPOWDER: "gunpowder",
  SPIDER_EYE: "spider_eye",
  BLAZE_POWDER: "blaze_powder",
  BLAZE_ROD: "blaze_rod",
  GHAST_TEAR: "ghast_tear",
  NETHER_WART: "nether_wart",
  MAGMA_CREAM: "magma_cream",
  FERMENTED_SPIDER_EYE: "fermented_spider_eye",
  GLISTERING_MELON: "glistering_melon_slice",
  GOLDEN_CARROT: "golden_carrot",
  RABBIT_FOOT: "rabbit_foot",
  TURTLE_HELMET: "turtle_helmet",
  PHANTOM_MEMBRANE: "phantom_membrane",
  LOG: "oak_log",
  LOG_2: "dark_oak_log",
  WOOD: "oak_wood",
  WOOL: "white_wool",
  STAINED_CLAY: "terracotta",
  ENCHANTED_BOOK: "enchanted_book",
  GOLDEN_APPLE: "golden_apple",
  ENCHANTED_GOLDEN_APPLE: "enchanted_golden_apple",

  // Additional skyblock items - using closest minecraft equivalents
  MITHRIL_ORE: "iron_ore",
  NULL_SPHERE: "ender_pearl",
  TARANTULA_WEB: "cobweb",
  SOUL_STRING: "string",
  GRIFFIN_FEATHER: "feather",
  GILLS: "prismarine_shard",
  NULL_OVOID: "ender_pearl",
  NULL_EDGE: "iron_sword",
  ENCHANTED_QUARTZ_BLOCK: "quartz_block",
  TARANTULA_SILK: "string",
};
